# This is a boilerplate parameters config generated for pipeline 'data_science'
# using Kedro 0.18.1.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.1/kedro_project_setup/configuration.html#parameters

model_options:
  test_size: 0.2
  val_size: 0.2
  random_state: 0
  n_neurons: 16
  hidden_activation_f: relu
  output_activation_f: sigmoid
  learning_rate: 0.001
  metrics: accuracy
  batch_size: 16
  epochs: 30
  features:
    - gender
    - polyuria
    - polydipsia
    - sudden_weight_loss
    - weakness
    - polyphagia
    - genital_thrush
    - visual_blurring
    - irritability
    - partial_paresis
    - muscle_stiffness
    - alopecia
    - age